name: ttv-notify

services:
  app:
    container_name: ttv-notify
    build: .
    environment:
      TELEGRAM_TOKEN: ""
      TELEGRAM_CHATID: ""
      TWITCH_CLIENT_ID: ""
      TWITCH_CLIENT_SECRET: ""
      TWITCH_STREAMERS: "streamer1,streamer2"
      MESSAGE_TEMPLATE: "{user_name} is live! \n\n{user_url}"
    network_mode: bridge
    restart: unless-stopped
